import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, readFile } from 'node:fs/promises';
import { chromium } from 'playwright';

test('production UI: geometry, YAML validation/import/export, rotation, and mobile layout', { timeout: 60_000 }, async () => {
  const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', 'preview', '--host', '127.0.0.1', '--port', '4178', '--strictPort'], { windowsHide: true, stdio: 'pipe' });
  let browser;
  try {
    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('Preview server did not start')), 15_000);
      server.stdout.on('data', data => { if (data.toString().includes('4178')) { clearTimeout(timer); resolve(); } });
      server.on('error', e => { clearTimeout(timer); reject(e); });
      server.on('exit', code => { clearTimeout(timer); reject(new Error(`Preview exited: ${code}`)); });
    });
    browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'chrome', headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1200 }, deviceScaleFactor: 1 });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto('http://127.0.0.1:4178/');
    await page.locator('#chassis-name').waitFor();
    assert.match(page.url(), /\/chassis\.html$/);
    assert.equal(await page.locator('#chassis-name').textContent(), 'T90L91');
    assert.match(await page.locator('#parameter-tables').textContent(), /39.025/);
    assert.match(await page.locator('#metrics').textContent(), /166.73 mm/);
    const canvas = page.locator('canvas');
    const initialImage = await canvas.evaluate(c => c.toDataURL());
    assert.ok(initialImage.length > 10_000, 'canvas is drawn');
    await mkdir('outputs', { recursive: true });
    await page.screenshot({ path: 'outputs/chassis-desktop.png', fullPage: true });
    assert.equal(await page.locator('#review-panel').isVisible(), false);

    await page.locator('#chassis-select').selectOption('T100L101');
    assert.equal(await page.locator('#chassis-name').textContent(), 'T100L101');
    assert.match(await page.locator('#metrics').textContent(), /176.73 mm/);
    assert.match(await page.locator('#parameter-tables').textContent(), /92.6/);
    assert.match(await page.locator('#reference').getAttribute('href'), /T100L101/);
    assert.equal(await page.locator('#review-panel').isVisible(), false);
    await page.screenshot({ path: 'outputs/chassis-t100-desktop.png', fullPage: true });
    await page.locator('#yaml-tab').click();
    const second = await page.locator('#yaml-editor').inputValue();
    await page.locator('#yaml-editor').fill(second + '\n# Unsaved draft stays with this chassis\n');
    await page.locator('#chassis-select').selectOption('T90L91');
    await page.locator('#chassis-select').selectOption('T100L101');
    assert.match(await page.locator('#yaml-editor').inputValue(), /Unsaved draft stays/);
    await page.locator('#restore').click();
    assert.equal(await page.locator('#yaml-editor').inputValue(), second);
    const secondDownload = page.waitForEvent('download');
    await page.locator('#download').click();
    assert.equal((await secondDownload).suggestedFilename(), 'T100L101.yaml');
    await page.reload();
    await page.locator('#chassis-name').waitFor();
    assert.equal(await page.locator('#chassis-name').textContent(), 'T100L101');
    await page.locator('#chassis-select').selectOption('T90L91');

    await page.locator('#yaml-tab').click();
    const original = await page.locator('#yaml-editor').inputValue();
    await page.locator('#yaml-editor').fill(original.replace('units: mm', 'units: cm'));
    await page.locator('#apply').click();
    assert.match(await page.locator('#error').textContent(), /units: must be mm/);
    assert.equal(await canvas.evaluate(c => c.toDataURL()), initialImage, 'invalid input retains last valid view');

    await page.locator('#yaml-editor').fill(original.replace('name: T90L91', 'name: Edited chassis').replace('x_mm: 91', 'x_mm: 100'));
    await page.locator('#apply').click();
    assert.equal(await page.locator('#chassis-name').textContent(), 'Edited chassis');
    assert.equal(await page.locator('#error').isVisible(), false);
    assert.match(await page.locator('#metrics').textContent(), /100 mm/);

    const downloadPromise = page.waitForEvent('download');
    await page.locator('#download').click();
    const download = await downloadPromise;
    assert.equal(download.suggestedFilename(), 'Edited_chassis.yaml');
    const saved = await readFile(await download.path(), 'utf8');
    assert.match(saved, /name: Edited chassis/);
    assert.match(saved, /y_mm: 39.025/);

    await page.locator('#import').setInputFiles({ name: 'roundtrip.yaml', mimeType: 'text/yaml', buffer: Buffer.from(saved) });
    assert.equal(await page.locator('#chassis-name').textContent(), 'Edited chassis');
    await page.locator('#restore').click();
    await page.locator('#heading').fill('0');
    assert.notEqual(await canvas.evaluate(c => c.toDataURL()), initialImage);
    await page.locator('#reset-view').click();
    assert.equal(await page.locator('#heading').inputValue(), '90');

    const imageDownload = page.waitForEvent('download');
    await page.locator('#export-png').click();
    assert.equal((await imageDownload).suggestedFilename(), 'T90L91.png');
    await page.locator('#parameters-tab').click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'outputs/chassis-mobile.png', fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'no mobile horizontal overflow');
    // The chassis page is retained alongside the independently addressable board studio.
    await page.getByRole('link', { name: 'Game boards', exact: true }).click();
    await page.locator('#board-name').waitFor();
    assert.match(page.url(), /\/board\.html$/);
    assert.equal(await page.locator('#board-name').textContent(), 'Loop');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'no board mobile overflow');
    await page.screenshot({ path: 'outputs/board-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1200 });
    const boardCanvas = page.locator('#board-canvas');
    for (const [key, name] of [['loop', 'Loop'], ['elle', 'Elle'], ['snake', 'Snake']]) {
      await page.locator('#board-select').selectOption(key);
      assert.equal(await page.locator('#board-name').textContent(), name);
      assert.match(await page.locator('#route-badge').textContent(), /One closed loop/);
      assert.match(await page.locator('#board-metrics').textContent(), /960 × 720 mm/);
      assert.match(await page.locator('#board-reference').getAttribute('href'), new RegExp(key));
      await page.screenshot({ path: `outputs/board-${key}.png`, fullPage: true });
    }
    await page.locator('#turn-radius-slider').fill('10');
    await page.locator('#tile-grid button[data-row="1"][data-col="1"]').click();
    assert.equal(await page.locator('#tile-type').inputValue(), 'turn_ne');
    assert.equal(await page.locator('#selected-tile-label').textContent(), 'Row 2 · Column 2');
    await page.locator('#tile-grid button[data-row="0"][data-col="0"]').click();
    assert.equal(await page.locator('#turn-radius').inputValue(), '10');
    const tightImage = await boardCanvas.evaluate(c => c.toDataURL());
    await page.locator('#line-width-slider').fill('25');
    assert.equal(await page.locator('#line-width').inputValue(), '25');
    assert.notEqual(await boardCanvas.evaluate(c => c.toDataURL()), tightImage);
    await page.locator('#turn-radius-slider').fill('120');
    assert.match(await page.locator('#route-badge').textContent(), /One closed loop/);
    await page.locator('#tile-radius').fill('30');
    await page.locator('#tile-radius').press('Tab');
    assert.match(await page.locator('#radius-help').textContent(), /1 corner override/);
    await page.locator('#tile-type').selectOption('empty');
    assert.match(await page.locator('#route-badge').textContent(), /unmatched/);
    assert.equal(await page.locator('#tile-radius').isDisabled(), true);
    await page.locator('#tile-type').selectOption('turn_se');
    assert.match(await page.locator('#route-badge').textContent(), /One closed loop/);
    await page.locator('#tile-radius').fill('30'); await page.locator('#tile-radius').press('Tab');
    await page.locator('#board-yaml-tab').click();
    const editedBoard = await page.locator('#board-yaml-editor').inputValue();
    assert.match(editedBoard, /default_width_mm: 25/); assert.match(editedBoard, /radius_mm: 30/);
    const boardDownloadPromise = page.waitForEvent('download');
    await page.locator('#board-download').click();
    const boardDownload = await boardDownloadPromise;
    assert.equal(boardDownload.suggestedFilename(), 'board_4_3_snake.yaml');
    const boardText = await readFile(await boardDownload.path(), 'utf8');
    await page.locator('#board-import').setInputFiles({ name: 'board.yaml', mimeType: 'text/yaml', buffer: Buffer.from(boardText) });
    assert.equal(await page.locator('#board-yaml-editor').inputValue(), boardText);
    const validBoardImage = await boardCanvas.evaluate(c => c.toDataURL());
    await page.locator('#board-yaml-editor').fill(boardText.replace('default_turn_radius_mm: 120', 'default_turn_radius_mm: 121'));
    await page.locator('#board-apply').click();
    assert.match(await page.locator('#board-error').textContent(), /half the grid/);
    assert.equal(await boardCanvas.evaluate(c => c.toDataURL()), validBoardImage);
    await page.locator('#board-select').selectOption('loop');
    await page.locator('#board-select').selectOption('snake');
    assert.match(await page.locator('#board-yaml-editor').inputValue(), /default_turn_radius_mm: 121/);
    await page.locator('#board-restore').click();
    await page.locator('#design-tab').click();
    await page.locator('.board-settings summary').click();
    await page.locator('#column-diameter').fill('40'); await page.locator('#column-diameter').press('Tab');
    assert.match(await page.locator('#board-yaml-editor').inputValue(), /display_diameter_mm: 40/);
    const imagePromise = page.waitForEvent('download'); await page.locator('#board-export-png').click();
    assert.equal((await imagePromise).suggestedFilename(), 'board_4_3_snake.png');
    await page.reload(); await page.locator('#board-name').waitFor();
    assert.equal(await page.locator('#board-name').textContent(), 'Snake');
    await page.getByRole('link', { name: 'Chassis', exact: true }).click();
    await page.locator('#chassis-name').waitFor();
    assert.equal(await page.locator('#chassis-name').textContent(), 'T90L91');
    await page.getByRole('link', { name: 'Sensors', exact: true }).click();
    await page.locator('#scene-name').waitFor();
    assert.match(page.url(), /\/observe\.html$/);
    assert.equal(await page.locator('#scene-name').textContent(), 'T90L91 × Loop');
    assert.equal(await page.locator('#hit-count').textContent(), '2 / 8 BLACK');
    assert.equal(await page.locator('.reading').count(), 8);
    assert.match(await page.locator('.reading.on').allTextContents().then(v => v.join(' ')), /s3.*s4/);
    assert.equal(await page.locator('#clearance-state').textContent(), 'CLEAR');
    assert.match(await page.locator('#closest-column').textContent(), /C1_0.*61 mm/);
    assert.equal(await page.locator('#clearance-list > div').count(), 5);
    await page.locator('#pose-y').fill('240');
    assert.equal(await page.locator('#clearance-state').textContent(), 'COLLISION');
    assert.match(await page.locator('#closest-column').textContent(), /C1_1.*-39.5 mm/);
    await page.locator('#pose-y').fill('120');
    await page.locator('#scene-chassis').selectOption('T100L101');
    await page.locator('#scene-board').selectOption('snake');
    assert.equal(await page.locator('#scene-name').textContent(), 'T100L101 × Snake');
    await page.locator('#scene-width').fill('25');
    await page.locator('#scene-radius').fill('10');
    await page.locator('#pose-x').fill('300'); await page.locator('#pose-y').fill('180');
    await page.locator('#pose-heading').fill('45');
    assert.equal(await page.locator('#heading-output').textContent(), '45°');
    // Reset puts the chassis at the board's lower route and gives a stable drag target.
    await page.locator('#reset-pose').click();
    const beforeX = await page.locator('#pose-x').inputValue();
    const resetBox = await page.locator('#observation-canvas').boundingBox();
    await page.mouse.move(resetBox.x + resetBox.width * 0.31, resetBox.y + resetBox.height * 0.80);
    await page.mouse.down(); await page.mouse.move(resetBox.x + resetBox.width * 0.40, resetBox.y + resetBox.height * 0.70, { steps: 5 }); await page.mouse.up();
    assert.notEqual(await page.locator('#pose-x').inputValue(), beforeX);
    await page.screenshot({ path: 'outputs/sensor-studio.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'no sensor page mobile overflow');
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close();
    server.kill();
  }
});
