import './style.css';
import './robustness.css';
import t90Yaml from '../../configs/chassis/T90L91.yaml?raw';
import t100Yaml from '../../configs/chassis/T100L101.yaml?raw';
import elleYaml from '../../configs/boards/board_4_3_elle.yaml?raw';
import { parseChassis } from '../core/config';
import { parseBoard } from '../core/board-config';
import { SIMULATION_ENGINE_VERSION } from '../core/simulation';
import type { SimulationConfig } from '../core/simulation';
import type { RobustnessTrial, RobustnessWorkerRequest, RobustnessWorkerResponse } from './robustness.worker';

const chassisPresets={T90L91:parseChassis(t90Yaml),T100L101:parseChassis(t100Yaml)}; type ChassisKey=keyof typeof chassisPresets;
const boardDesign=parseBoard(elleYaml), query=new URLSearchParams(location.search), STORE='line-follower-robustness-studies-v3';
interface Aggregate { severity:number; runs:number; worstClearanceMm:number|null; medianClearanceMm:number|null; bestClearanceMm:number|null; worstSeed:number|null; lineLosses:number }
interface Study { id:string; createdAt:string; engineVersion:string; chassis:ChassisKey; board:'elle'; lineWidthMm:number; turnRadiusMm:number; kp:number; durationS:number; seedCount:number; severityStart:number; severityStop:number; severityStep:number; aggregates:Aggregate[] }

document.querySelector('#app')!.innerHTML=`<header class="site-header"><a class="brand" href="./"><span class="brand-mark">↱</span> LINE FOLLOWER <span class="brand-light">/ SIM</span></a><nav class="studio-nav"><a href="./chassis.html">Chassis</a><a href="./board.html">Boards</a><a href="./observe.html">Sensors</a><a href="./simulate.html">Run</a><a href="./sweep.html">Sweeps</a><a href="./pid-tuning.html">PID tuning</a><a href="./robustness.html" aria-current="page">Robustness</a></nav></header>
<main><section class="page-heading"><div><p class="eyebrow">SIMULATION WORKSPACE / ROBUSTNESS</p><h1>Noise robustness<span>.</span></h1><p class="intro">Measure the worst clearance across deterministic sensor and chassis-noise seeds.</p></div><span class="units-pill">ELLE · 50 Hz</span></section>
<div class="robust-layout"><aside class="inspector robust-controls">
 <div class="robust-section"><h3>Candidate</h3><div class="robust-grid"><label>Chassis<select id="chassis"><option>T90L91</option><option>T100L101</option></select></label><label>Duration (s)<input id="duration" type="number" value="100" min="1"></label><label>Line width (mm)<input id="width" type="number" value="14" min="1"></label><label>Turn radius (mm)<input id="radius" type="number" value="15" min="1" max="120"></label><label>Kp<input id="kp" type="number" value="0.7" min="0" step="0.05"></label></div></div>
 <div class="robust-section"><h3>Noise sweep</h3><div class="robust-grid"><label>Severity start<input id="severity-start" type="number" value="0" min="0" step="0.05"></label><label>Severity stop<input id="severity-stop" type="number" value="2" min="0" step="0.05"></label><label>Severity step<input id="severity-step" type="number" value="0.2" min="0.01" step="0.05"></label><label>Seeds / severity<input id="seeds" type="number" value="40" min="1" max="1000"></label></div><p class="run-note">Severity 1.0 means up to ±1.5 mm sensor edge bias, 3% forward loss, and ±5% turn-dependent yaw variation. Zero severity needs one run.</p></div>
 <div class="robust-section"><strong id="trial-count">401 trials</strong><div class="progress-track"><i id="progress"></i></div><p id="progress-text" class="run-note">Ready</p><div class="robust-actions"><button id="run" class="button primary">Run robustness study</button><button id="cancel" class="button secondary" disabled>Cancel</button></div><p id="error" class="config-error" hidden></p></div>
</aside><section class="robust-panel"><div class="robust-card"><h2>Clearance versus noise severity</h2><div id="metric-cards" class="metric-cards"></div><div class="chart-wrap"><svg id="chart" class="robust-chart" viewBox="0 0 800 360" role="img" aria-label="Worst and median clearance by noise severity"></svg></div><div id="aggregate"></div></div></section></div>
<section class="robust-card" style="margin-top:18px"><div class="comparison-head"><div><p class="eyebrow">SAVED STUDIES</p><h2>Candidate comparison</h2></div><label class="margin-control">Required engineering margin (mm)<input id="margin" type="number" value="25" step="1"></label></div><p class="run-note">Qualified severity is the highest tested level for which the worst clearance remains at or above the selected margin at every preceding severity.</p><div id="comparison"></div></section>
<section class="board-note"><span class="tiny-tag">DETERMINISTIC NOISE</span><p>Each seed creates smooth, time-varying sensor thresholds and motion slip. Repeating the same complete conditions reuses the repository cache and produces the same result.</p></section></main>`;

function el<T extends Element = HTMLElement>(id:string):T{return document.getElementById(id) as unknown as T;} const num=(id:string)=>Number(el<HTMLInputElement>(id).value);
for(const [key,id] of Object.entries({chassis:'chassis',width:'width',radius:'radius',kp:'kp',duration:'duration'})){const v=query.get(key);if(v!==null)el<HTMLInputElement|HTMLSelectElement>(id).value=v;}
let workers:Worker[]=[],trials:RobustnessTrial[]=[],activeStudy:Study|null=null,cacheAvailable=false,pending:{key:string;condition:unknown;result:RobustnessTrial}[]=[];
function canonical(v:unknown):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;const o=v as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`;}
async function digest(v:unknown){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(v)));return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function range(start:number,stop:number,step:number){if(!(step>0)||stop<start)throw new Error('Severity range must have a positive step and stop at or above start.');const a:number[]=[];for(let v=start;v<=stop+step*1e-9;v+=step)a.push(Number(v.toFixed(10)));return a;}
function jobs(){const count=Math.floor(num('seeds'));return range(num('severity-start'),num('severity-stop'),num('severity-step')).flatMap(severity=>severity===0?[{severity,seed:0}]:Array.from({length:count},(_,seed)=>({severity,seed})));}
function fixedSimulation():SimulationConfig{return{durationS:num('duration'),controlDtS:.02,lineLossGraceS:1,maxMotionSubstepMm:2,maxRotationSubstepRad:Math.PI/90,motorOutputDelayS:.05,controller:{targetSpeedMmS:120,accelerationMmS2:300,decelerationMmS2:2000,kp:num('kp'),ki:0,kd:.002,integralLimitMmS:100,maxYawRateRadS:3,maxWheelSpeedMmS:250}};}
function aggregate(source=trials):Aggregate[]{const groups=new Map<number,RobustnessTrial[]>();for(const t of source){const a=groups.get(t.severity)??[];a.push(t);groups.set(t.severity,a);}return[...groups].sort(([a],[b])=>a-b).map(([severity,runs])=>{const valid=runs.filter(r=>r.summary.status==='completed').map(r=>({seed:r.seed,value:r.summary.minimumClearanceMm})).filter((x):x is {seed:number;value:number}=>x.value!==null&&Number.isFinite(x.value)).sort((a,b)=>a.value-b.value);return{severity,runs:runs.length,worstClearanceMm:valid[0]?.value??null,medianClearanceMm:valid.length?valid[Math.floor((valid.length-1)/2)].value:null,bestClearanceMm:valid.at(-1)?.value??null,worstSeed:valid[0]?.seed??null,lineLosses:runs.filter(r=>r.summary.status!=='completed').length};});}
function qualification(aggs:Aggregate[],margin:number){let qualified:number|null=null;for(const a of [...aggs].sort((x,y)=>x.severity-y.severity)){if(a.worstClearanceMm===null||a.worstClearanceMm<margin||a.lineLosses>0)break;qualified=a.severity;}return qualified;}
function fmt(v:number|null,d=2){return v===null?'—':v.toFixed(d);}
function studies():Study[]{try{return JSON.parse(localStorage.getItem(STORE)??'[]') as Study[];}catch{return[];}}
function saveStudy(study:Study){const saved=studies().filter(s=>s.id!==study.id);saved.unshift(study);localStorage.setItem(STORE,JSON.stringify(saved));}
function studyId(s:Pick<Study,'chassis'|'lineWidthMm'|'turnRadiusMm'|'kp'|'durationS'|'severityStart'|'severityStop'|'severityStep'|'seedCount'>){return canonical(s);}
function currentStudy(aggs:Aggregate[]):Study{const base={chassis:el<HTMLSelectElement>('chassis').value as ChassisKey,board:'elle' as const,lineWidthMm:num('width'),turnRadiusMm:num('radius'),kp:num('kp'),durationS:num('duration'),seedCount:Math.floor(num('seeds')),severityStart:num('severity-start'),severityStop:num('severity-stop'),severityStep:num('severity-step')};return{...base,id:studyId(base),createdAt:new Date().toISOString(),engineVersion:SIMULATION_ENGINE_VERSION,aggregates:aggs};}
function replayHref(a:Aggregate){if(a.worstSeed===null)return'';const s=activeStudy??currentStudy([]);return`./simulate.html?${new URLSearchParams({chassis:s.chassis,board:'elle',width:String(s.lineWidthMm),radius:String(s.turnRadiusMm),kp:String(s.kp),duration:String(s.durationS),x:'240',y:'120',heading:'0',severity:String(a.severity),seed:String(a.worstSeed),motorDelay:'0.05'})}`;}
function render(){const aggs=activeStudy?.aggregates??aggregate(),margin=num('margin'),zero=aggs.find(a=>a.severity===0),one=aggs.find(a=>Math.abs(a.severity-1)<1e-9),qualified=qualification(aggs,margin);
 el('metric-cards').innerHTML=`<div class="metric-card"><span>Worst at zero noise</span><strong>${fmt(zero?.worstClearanceMm??null)} mm</strong></div><div class="metric-card"><span>Worst at severity 1.0</span><strong>${fmt(one?.worstClearanceMm??null)} mm</strong></div><div class="metric-card"><span>Qualified severity at ${margin} mm</span><strong>${qualified===null?'None':qualified.toFixed(2)}</strong></div>`;
 renderChart(aggs,margin);el('aggregate').innerHTML=aggs.length?`<table class="aggregate-table"><thead><tr><th>Severity</th><th>Completed</th><th>Worst completed</th><th>Completed median</th><th>Best completed</th><th>Worst seed</th><th>Replay</th><th>Line losses</th></tr></thead><tbody>${aggs.map(a=>`<tr><td>${a.severity.toFixed(2)}</td><td>${a.runs-a.lineLosses} / ${a.runs}</td><td>${fmt(a.worstClearanceMm)} mm</td><td>${fmt(a.medianClearanceMm)} mm</td><td>${fmt(a.bestClearanceMm)} mm</td><td>${a.worstSeed??'—'}</td><td>${a.worstSeed===null?'—':`<a class="text-button" href="${replayHref(a)}">Worst seed →</a>`}</td><td>${a.lineLosses}</td></tr>`).join('')}</tbody></table>`:'<p class="empty-copy">Run the candidate to populate the chart and statistics.</p>';renderComparison();}
function renderChart(a:Aggregate[],margin:number){const svg=el<SVGSVGElement>('chart'),W=800,H=360,p={l:62,r:20,t:20,b:48};if(!a.length){svg.innerHTML='<text x="400" y="180" text-anchor="middle" class="chart-text">No results yet</text>';return;}const xs=a.map(x=>x.severity),ys=a.flatMap(x=>[x.worstClearanceMm,x.medianClearanceMm,x.bestClearanceMm]).filter((x):x is number=>x!==null);ys.push(margin);let xmin=Math.min(...xs),xmax=Math.max(...xs);if(xmax===xmin)xmax=xmin+1;let ymin=Math.min(...ys),ymax=Math.max(...ys);const pad=Math.max(2,(ymax-ymin)*.12);ymin-=pad;ymax+=pad;const X=(x:number)=>p.l+(x-xmin)/(xmax-xmin)*(W-p.l-p.r),Y=(y:number)=>p.t+(ymax-y)/(ymax-ymin)*(H-p.t-p.b),path=(key:'worstClearanceMm'|'medianClearanceMm')=>a.filter(q=>q[key]!==null).map((q,i)=>`${i?'L':'M'}${X(q.severity)},${Y(q[key]!)}`).join(' '),band=[...a.filter(q=>q.bestClearanceMm!==null).map(q=>`${X(q.severity)},${Y(q.bestClearanceMm!)}`),...a.filter(q=>q.worstClearanceMm!==null).reverse().map(q=>`${X(q.severity)},${Y(q.worstClearanceMm!)}`)].join(' ');let html='';for(let i=0;i<=4;i++){const y=ymin+(ymax-ymin)*i/4;html+=`<line class="chart-grid" x1="${p.l}" y1="${Y(y)}" x2="${W-p.r}" y2="${Y(y)}"/><text class="chart-text" x="${p.l-8}" y="${Y(y)+4}" text-anchor="end">${y.toFixed(1)}</text>`;}for(const x of xs)html+=`<text class="chart-text" x="${X(x)}" y="${H-18}" text-anchor="middle">${x}</text>`;html+=`<line class="chart-axis" x1="${p.l}" y1="${p.t}" x2="${p.l}" y2="${H-p.b}"/><line class="chart-axis" x1="${p.l}" y1="${H-p.b}" x2="${W-p.r}" y2="${H-p.b}"/><polygon class="chart-band" points="${band}"/><line class="chart-margin" x1="${p.l}" y1="${Y(margin)}" x2="${W-p.r}" y2="${Y(margin)}"/><path class="chart-median" d="${path('medianClearanceMm')}"/><path class="chart-worst" d="${path('worstClearanceMm')}"/>${a.filter(q=>q.worstClearanceMm!==null).map(q=>`<circle class="chart-point" cx="${X(q.severity)}" cy="${Y(q.worstClearanceMm!)}" r="4"><title>Severity ${q.severity}: ${q.worstClearanceMm!.toFixed(3)} mm, seed ${q.worstSeed}</title></circle>`).join('')}<text class="chart-text" x="14" y="15">clearance (mm)</text><text class="chart-text" x="${W/2}" y="${H-2}" text-anchor="middle">noise severity</text>`;svg.innerHTML=html;}
function renderComparison(){const margin=num('margin'),all=studies();el('comparison').innerHTML=all.length?`<table class="comparison-table"><thead><tr><th>Candidate</th><th>Width</th><th>Radius</th><th>Kp</th><th>Worst at 0</th><th>Worst at 1.0</th><th>Qualified severity @ ${margin} mm</th><th></th></tr></thead><tbody>${all.map(s=>{const z=s.aggregates.find(a=>a.severity===0),o=s.aggregates.find(a=>Math.abs(a.severity-1)<1e-9),q=qualification(s.aggregates,margin);return`<tr class="${activeStudy?.id===s.id?'study-current':''}" data-study="${encodeURIComponent(s.id)}"><td>${s.chassis}</td><td>${s.lineWidthMm} mm</td><td>${s.turnRadiusMm} mm</td><td>${s.kp}</td><td>${fmt(z?.worstClearanceMm??null)} mm</td><td>${fmt(o?.worstClearanceMm??null)} mm</td><td>${q===null?'None':q.toFixed(2)}</td><td><button class="delete-study" data-delete="${encodeURIComponent(s.id)}">×</button></td></tr>`;}).join('')}</tbody></table>`:'<p class="empty-copy">Completed studies will appear here for comparison.</p>';el('comparison').querySelectorAll<HTMLTableRowElement>('tr[data-study]').forEach(row=>row.onclick=e=>{if((e.target as HTMLElement).matches('[data-delete]'))return;const s=studies().find(x=>x.id===decodeURIComponent(row.dataset.study!));if(s){activeStudy=s;render();}});el('comparison').querySelectorAll<HTMLButtonElement>('[data-delete]').forEach(b=>b.onclick=()=>{localStorage.setItem(STORE,JSON.stringify(studies().filter(s=>s.id!==decodeURIComponent(b.dataset.delete!))));if(activeStudy?.id===decodeURIComponent(b.dataset.delete!))activeStudy=null;render();});}
async function lookup(keys:string[]){const r=await fetch('/api/sweep-cache/lookup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({keys})});if(!r.ok)throw new Error();cacheAvailable=true;return(await r.json() as {entries:Record<string,RobustnessTrial>}).entries;}
async function flush(){if(!cacheAvailable||!pending.length)return;const entries=pending.splice(0);const r=await fetch('/api/sweep-cache/store',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entries})});if(!r.ok)throw new Error('Could not update repository cache.');}
function setBusy(v:boolean){el<HTMLButtonElement>('run').disabled=v;el<HTMLButtonElement>('cancel').disabled=!v;}
async function run(){try{workers.forEach(w=>w.terminate());workers=[];trials=[];activeStudy=null;pending=[];setBusy(true);el('error').hidden=true;const chassisKey=el<HTMLSelectElement>('chassis').value as ChassisKey,chassis=chassisPresets[chassisKey],simulation=fixedSimulation(),pose={x:240,y:120,heading:0},raw=jobs();el('progress-text').textContent=`Checking cache for ${raw.length} trials…`;const keyed=await Promise.all(raw.map(async j=>{const condition={engineVersion:SIMULATION_ENGINE_VERSION,chassis,boardDesign,pose,lineWidthMm:num('width'),turnRadiusMm:num('radius'),simulation:{...simulation,noise:{severity:j.severity,seed:j.seed}}};return{...j,key:await digest(condition),condition:{engineVersion:SIMULATION_ENGINE_VERSION,kind:'robustness',chassis:chassisKey,board:'elle',pose,lineWidthMm:num('width'),turnRadiusMm:num('radius'),kp:num('kp'),durationS:num('duration'),severity:j.severity,seed:j.seed}};}));let cached:Record<string,RobustnessTrial>={};try{cached=await lookup(keyed.map(j=>j.key));}catch{cacheAvailable=false;}const missing:typeof keyed=[];for(const j of keyed){if(cached[j.key])trials.push(cached[j.key]);else missing.push(j);}const progress=()=>{el<HTMLElement>('progress').style.width=`${trials.length/keyed.length*100}%`;el('progress-text').textContent=`${trials.length} / ${keyed.length} trials${cacheAvailable?' · repository cache active':' · memory only'}`;render();};progress();const finish=async()=>{await flush();const study=currentStudy(aggregate());activeStudy=study;saveStudy(study);setBusy(false);el('progress-text').textContent=`Complete · ${keyed.length-missing.length} reused · ${missing.length} computed`;render();};if(!missing.length){await finish();return;}const count=Math.min(4,navigator.hardwareConcurrency||2,missing.length),chunks=Array.from({length:count},()=>[] as typeof missing);missing.forEach((j,i)=>chunks[i%count].push(j));let finished=0;for(const chunk of chunks){const worker=new Worker(new URL('./robustness.worker.ts',import.meta.url),{type:'module'});workers.push(worker);worker.onmessage=async(event:MessageEvent<RobustnessWorkerResponse>)=>{const m=event.data;if(m.type==='progress'){trials.push(m.trial);const source=keyed.find(j=>j.key===m.trial.key)!;pending.push({key:m.trial.key,condition:source.condition,result:m.trial});if(pending.length>=20)await flush();progress();}else if(m.type==='complete'){finished++;if(finished===chunks.length)await finish();}else fail(m.message);};worker.postMessage({chassis,boardDesign,initialPose:pose,lineWidthMm:num('width'),turnRadiusMm:num('radius'),simulation,jobs:chunk.map(({severity,seed,key})=>({severity,seed,key}))} satisfies RobustnessWorkerRequest);}}catch(e){fail(e);}}
function fail(e:unknown){workers.forEach(w=>w.terminate());setBusy(false);el('error').textContent=e instanceof Error?e.message:String(e);el('error').hidden=false;}
function updateCount(){try{el('trial-count').textContent=`${jobs().length} trials`;el('error').hidden=true;}catch(e){fail(e);}}
el('run').onclick=()=>void run();el('cancel').onclick=()=>{workers.forEach(w=>w.terminate());workers=[];setBusy(false);el('progress-text').textContent='Cancelled';};for(const id of ['severity-start','severity-stop','severity-step','seeds'])el(id).addEventListener('input',updateCount);el('margin').addEventListener('input',render);updateCount();render();
